services:
  - type: web
    name: face-recognition-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main-app.py --server.port=10000 --server.headless=true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
