services:
  - type: web
    name: face-recognition-app
    env: python
    buildCommand: ./build.sh
    startCommand: streamlit run main-app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
